# Generated by Django 5.2.7 on 2025-10-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_studentapplication_gender_studentapplication_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='guardian_contact',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
