# Generated by Django 5.2.7 on 2025-10-24 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_studentapplication_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_set', to='hostel.hostel'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='assigned_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentapplication', to='hostel.room'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='fee_receipt',
            field=models.FileField(blank=True, null=True, upload_to='documents/receipts/'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='provisional_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/letters/'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentapplication', to=settings.AUTH_USER_MODEL),
        ),
    ]
