# Generated by Django 5.2.7 on 2025-10-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_alter_room_hostel_alter_studentapplication_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_images/'),
        ),
    ]
