# Generated by Django 5.2.7 on 2025-10-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_hostel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='level',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PHD', 'PhD')], max_length=3),
        ),
    ]
