# Generated by Django 5.2.7 on 2025-10-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_alter_hostel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
