# Generated by Django 5.2.7 on 2025-10-27 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_hostel_warden_email_hostel_warden_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='assigned_warden',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Warden', 'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hostels', to=settings.AUTH_USER_MODEL),
        ),
    ]
