# Generated by Django 5.2.7 on 2025-10-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_hostel_assigned_warden'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='Lower numbers mean higher priority (filled first).'),
        ),
    ]
