# Generated by Django 5.2.7 on 2025-10-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_hostel_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
