# Generated by Django 5.2.7 on 2025-10-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_studentapplication_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='location_details',
            field=models.TextField(blank=True, help_text='Enter location description (e.g., Near Silver Jubilee Campus, Opposite Central Library)', null=True),
        ),
    ]
