# Generated by Django 5.2.7 on 2025-11-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_hostel_location_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='rejection_message',
            field=models.TextField(blank=True, help_text='If rejecting, provide the reason here. This will be visible to the student.', null=True),
        ),
    ]
