# Generated by Django 5.2.7 on 2025-11-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0013_studentapplication_rejection_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='is_manually_closed',
            field=models.BooleanField(default=False, help_text='Check this box to manually close this hostel to new applications, even if it is not full.'),
        ),
    ]
